apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: logstash-syslogtosentinel
spec:
  selector:
    matchLabels:
      app: logstash-syslogtosentinel
  template:
    metadata:
      labels:
        app: logstash-syslogtosentinel
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - image: logstashdemo.azurecr.io/logstash/syslog-to-sentinel_0.2
        name: logstashdemo
        ports:
        - containerPort: 12345
          protocol: TCP
        env:
        - name: WORKSPACEID
          value: "2cfabee8-4b6d-4e41-9926-4b46c2e6785a"
        - name: WORKSPACEKEY
          value: "7y2BvGrUiS6trnDntnaGDSbGI906R4V6o8XJ1lvO059/Wp+e7xlcvLFcodz+igXAGxhJG2Glch16/2Ryd8vi+g=="
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: syslog-loadbalancer
spec:
  type: LoadBalancer

  ports:
  - port: 12345
    protocol: TCP
  selector:
    app: logstash-syslogtosentinel